# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='main', max_length=127),
        ),
    ]
